const socketEvents = {
  POST_NEW_MESSAGE: 'POST_NEW_MESSAGE',
  MESSAGES_UPDATED: 'MESSAGES_UPDATED',
  REQUEST_INITIAL_MESSAGES: 'REQUEST_INITIAL_MESSAGES',
  FULFILL_INITIAL_MESSAGES: 'FULFILL_INITIAL_MESSAGES',
};

// using CommonJs to support node
module.exports = {
    socketEvents,
}